// <auto-generated />
namespace SAS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class wrongCreatedUTCName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wrongCreatedUTCName));
        
        string IMigrationMetadata.Id
        {
            get { return "202103302318334_wrongCreatedUTCName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
